# Copyright (C) 2024-2026 Chaos Cypher, Inc.
# SPDX-License-Identifier: AGPL-3.0-only
"""baseline

Revision ID: 0001
Revises:
Create Date: 2026-06-02 00:00:00.000000+00:00

Consolidated baseline for the public launch. On 2026-06-02 the original
50-file Alembic chain (0001-0050) was squashed into this single migration.
Its ``upgrade()`` is a full ``create_table`` of the entire current schema,
regenerated from ``SQLModel.metadata`` via ``alembic revision
--autogenerate`` against an empty database, so a fresh ``upgrade head``
reproduces exactly what ``SQLModel.metadata.create_all`` would build.
Verified by ``test_baseline_matches_metadata`` and
``test_no_undeclared_changes``.

Databases created before the squash (stamped at a now-deleted revision
such as ``0050_...``) auto-recover on the next startup: ``ensure_stamped``
re-stamps any unrecognized revision to this baseline (the schema is
unchanged, so no data is lost).
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 - autogen output references sqlmodel.sql.sqltypes.AutoString


# Revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# ChaosCypher migration metadata - consumed by the runner's tier classifier.
# Tier values: "safe_auto" | "needs_confirmation" | "manual"
CC_TIER: str = "safe_auto"
CC_DESCRIPTION: str = "Initial schema baseline (every table at adoption time)"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('source_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_db_user', 'chats', ['database_name', 'user_id'], unique=False)
    op.create_index(op.f('ix_chats_database_name'), 'chats', ['database_name'], unique=False)
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_table('graph_snapshots',
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('database_name')
    )
    op.create_index(op.f('ix_graph_snapshots_generated_at'), 'graph_snapshots', ['generated_at'], unique=False)
    op.create_table('llm_daily_spend',
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spend_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('database_name', 'spend_date')
    )
    op.create_table('pending_search_index',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'item_id', name='uq_pending_search_index')
    )
    op.create_index(op.f('ix_pending_search_index_created_at'), 'pending_search_index', ['created_at'], unique=False)
    op.create_index(op.f('ix_pending_search_index_item_id'), 'pending_search_index', ['item_id'], unique=False)
    op.create_index(op.f('ix_pending_search_index_kind'), 'pending_search_index', ['kind'], unique=False)
    op.create_index(op.f('ix_pending_search_index_source_id'), 'pending_search_index', ['source_id'], unique=False)
    op.create_table('source_tags',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_tags_database_name'), 'source_tags', ['database_name'], unique=False)
    op.create_index(op.f('ix_source_tags_name'), 'source_tags', ['name'], unique=False)
    op.create_table('sources',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filepath', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('origin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.Column('indexing_complete', sa.Boolean(), nullable=False),
    sa.Column('extraction_complete', sa.Boolean(), nullable=False),
    sa.Column('commit_complete', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_failed_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('recovery_attempts', sa.Integer(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('paused_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('indexing_started_at', sa.DateTime(), nullable=True),
    sa.Column('indexing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('total_content_length', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('vision_pages_truncated', sa.Integer(), nullable=False),
    sa.Column('vision_pages_sampled_quick_mode', sa.Integer(), nullable=False),
    sa.Column('chunks_rerun_total', sa.Integer(), nullable=False),
    sa.Column('extraction_started_at', sa.DateTime(), nullable=True),
    sa.Column('extraction_completed_at', sa.DateTime(), nullable=True),
    sa.Column('extraction_depth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extraction_entities_count', sa.Integer(), nullable=False),
    sa.Column('extraction_relationships_count', sa.Integer(), nullable=False),
    sa.Column('extraction_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extraction_domain_auto', sa.Boolean(), nullable=False),
    sa.Column('domain_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('domain_content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('forced_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auto_analyze', sa.Boolean(), nullable=False),
    sa.Column('confirmation_required', sa.Boolean(), nullable=False),
    sa.Column('extraction_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('enable_normalization', sa.Boolean(), nullable=True),
    sa.Column('enable_vision', sa.Boolean(), nullable=False),
    sa.Column('content_filtering', sa.Boolean(), nullable=False),
    sa.Column('filtering_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enable_direction_correction', sa.Boolean(), nullable=True),
    sa.Column('protect_orphans', sa.Boolean(), nullable=True),
    sa.Column('enable_inverse_relationships', sa.Boolean(), nullable=True),
    sa.Column('max_entity_degree_override', sa.Integer(), nullable=True),
    sa.Column('cross_chunk_filtering_log', sa.JSON(), nullable=True),
    sa.Column('commit_payload', sa.Text(), nullable=True),
    sa.Column('current_extraction_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_filtering_enabled', sa.Boolean(), nullable=True),
    sa.Column('extraction_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extraction_queued_at', sa.DateTime(), nullable=True),
    sa.Column('extraction_pending_file_info', sa.JSON(), nullable=True),
    sa.Column('detection_proposal', sa.JSON(), nullable=True),
    sa.Column('embeddings_generated', sa.Boolean(), nullable=False),
    sa.Column('embeddings_count', sa.Integer(), nullable=False),
    sa.Column('embeddings_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embeddings_generated_at', sa.DateTime(), nullable=True),
    sa.Column('commit_started_at', sa.DateTime(), nullable=True),
    sa.Column('commit_completed_at', sa.DateTime(), nullable=True),
    sa.Column('commit_nodes_created', sa.Integer(), nullable=False),
    sa.Column('commit_edges_created', sa.Integer(), nullable=False),
    sa.Column('commit_templates_created', sa.Integer(), nullable=False),
    sa.Column('source_document_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('step_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('llm_total_calls', sa.Integer(), nullable=False),
    sa.Column('llm_successful_calls', sa.Integer(), nullable=False),
    sa.Column('llm_failed_calls', sa.Integer(), nullable=False),
    sa.Column('llm_retry_calls', sa.Integer(), nullable=False),
    sa.Column('llm_first_try_successes', sa.Integer(), nullable=False),
    sa.Column('llm_retry_successes', sa.Integer(), nullable=False),
    sa.Column('llm_permanent_failures', sa.Integer(), nullable=False),
    sa.Column('llm_total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_wasted_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_avg_call_duration_ms', sa.Integer(), nullable=True),
    sa.Column('llm_total_duration_ms', sa.Integer(), nullable=False),
    sa.Column('llm_estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('llm_error_counts', sa.JSON(), nullable=True),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_metadata', sa.JSON(), nullable=True),
    sa.Column('cached_quality_grade', sa.Float(), nullable=True),
    sa.Column('cached_quality_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cached_richness_score', sa.Float(), nullable=True),
    sa.Column('cached_avg_entity_quality', sa.Float(), nullable=True),
    sa.Column('cached_avg_relationship_quality', sa.Float(), nullable=True),
    sa.Column('cached_connectivity_ratio', sa.Float(), nullable=True),
    sa.Column('cached_topology_score', sa.Float(), nullable=True),
    sa.Column('cached_density_ratio', sa.Float(), nullable=True),
    sa.Column('cached_density_score', sa.Float(), nullable=True),
    sa.Column('cached_pollution_penalty', sa.Float(), nullable=True),
    sa.Column('cached_structural_penalty', sa.Float(), nullable=True),
    sa.Column('cached_hub_skew', sa.Float(), nullable=True),
    sa.Column('cached_reciprocal_rate', sa.Float(), nullable=True),
    sa.Column('cached_low_quality_entity_count', sa.Integer(), nullable=True),
    sa.Column('cached_low_quality_relationship_count', sa.Integer(), nullable=True),
    sa.Column('cached_coverage_score', sa.Float(), nullable=True),
    sa.Column('cached_scores_at', sa.DateTime(), nullable=True),
    sa.Column('cached_scores_version', sa.Integer(), nullable=True),
    sa.Column('loader_encoding_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('loader_warnings_count', sa.Integer(), nullable=False),
    sa.Column('loader_files_skipped', sa.Integer(), nullable=False),
    sa.Column('cleaner_lines_removed', sa.Integer(), nullable=False),
    sa.Column('cleaner_paragraphs_deduplicated', sa.Integer(), nullable=False),
    sa.Column('cleaner_chars_removed', sa.Integer(), nullable=False),
    sa.Column('chunks_coalesced_count', sa.Integer(), nullable=False),
    sa.Column('llm_chunks_truncated', sa.Integer(), nullable=False),
    sa.Column('llm_chunks_aborted_by_loop', sa.Integer(), nullable=False),
    sa.Column('parser_lines_dropped', sa.Integer(), nullable=False),
    sa.Column('dedup_entities_merged', sa.Integer(), nullable=False),
    sa.Column('structural_entities_filtered', sa.Integer(), nullable=False),
    sa.Column('orphan_entities_filtered', sa.Integer(), nullable=False),
    sa.Column('relationships_dropped_invalid', sa.Integer(), nullable=False),
    sa.Column('relationships_dropped_capped', sa.Integer(), nullable=False),
    sa.Column('citations_skipped_no_chunk_index', sa.Integer(), nullable=False),
    sa.Column('vector_indexed_at', sa.DateTime(), nullable=True),
    sa.Column('vector_indexing_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence_entities_dropped', sa.Integer(), nullable=False),
    sa.Column('evidence_relationships_dropped', sa.Integer(), nullable=False),
    sa.Column('aggregator_relationships_dropped', sa.Integer(), nullable=False),
    sa.Column('llm_chunks_timed_out', sa.Integer(), nullable=False),
    sa.Column('llm_chunks_failed_permanent', sa.Integer(), nullable=False),
    sa.Column('standalone_chunk_failures', sa.Integer(), nullable=False),
    sa.Column('semantic_dedup_fallbacks', sa.Integer(), nullable=False),
    sa.Column('relationships_direction_corrected', sa.Integer(), nullable=False),
    sa.Column('relationships_dropped_type_unmatched', sa.Integer(), nullable=False),
    sa.Column('relationships_type_fuzzy_matched', sa.Integer(), nullable=False),
    sa.Column('relationships_type_fell_through', sa.Integer(), nullable=False),
    sa.Column('user_regex_timeout_hits', sa.Integer(), nullable=False),
    sa.Column('ocr_cleaner_skipped_by_predicate', sa.Integer(), nullable=False),
    sa.Column('chunker_normalize_drops', sa.Integer(), nullable=False),
    sa.Column('chunker_prestrip_lines_removed', sa.Integer(), nullable=False),
    sa.Column('chunks_skipped_by_depth', sa.Integer(), nullable=False),
    sa.Column('loader_replacement_chars_count', sa.Integer(), nullable=False),
    sa.Column('citations_skipped_index_not_mapped', sa.Integer(), nullable=False),
    sa.Column('loader_pdf_pages_failed', sa.Integer(), nullable=False),
    sa.Column('loader_html_dropped_tags', sa.JSON(), nullable=True),
    sa.Column('loader_docx_paragraphs_skipped', sa.Integer(), nullable=False),
    sa.Column('loader_xlsx_rows_skipped', sa.Integer(), nullable=False),
    sa.Column('loader_pptx_shapes_skipped', sa.JSON(), nullable=True),
    sa.Column('loader_csv_rows_truncated', sa.Integer(), nullable=False),
    sa.Column('cleaner_plugin_load_failures', sa.Integer(), nullable=False),
    sa.Column('embedding_chunk_failures', sa.Integer(), nullable=False),
    sa.Column('embedding_dimension_mismatches', sa.Integer(), nullable=False),
    sa.Column('chunks_completed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('analysis_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_content_hash'), 'sources', ['content_hash'], unique=False)
    op.create_index(op.f('ix_sources_current_extraction_job_id'), 'sources', ['current_extraction_job_id'], unique=False)
    op.create_index(op.f('ix_sources_database_name'), 'sources', ['database_name'], unique=False)
    op.create_index('ix_sources_database_name_created_at_desc', 'sources', ['database_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_sources_processing_status'), 'sources', ['processing_status'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processing_paused', sa.Boolean(), nullable=False),
    sa.Column('processing_paused_at', sa.DateTime(), nullable=True),
    sa.Column('processing_paused_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paused_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_tools',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_tools_category'), 'system_tools', ['category'], unique=False)
    op.create_table('tool_statistics',
    sa.Column('tool_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('successful_calls', sa.Integer(), nullable=False),
    sa.Column('failed_calls', sa.Integer(), nullable=False),
    sa.Column('avg_execution_ms', sa.Integer(), nullable=False),
    sa.Column('last_called_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tool_type', 'tool_id'),
    sa.UniqueConstraint('tool_type', 'tool_id', name='uix_tool_type_id')
    )
    op.create_table('workflows',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expose_as_ai_tool', sa.Boolean(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('allow_parallel_execution', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('database_name', 'name', name='uq_workflows_database_name_name')
    )
    op.create_index(op.f('ix_workflows_database_name'), 'workflows', ['database_name'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_chat_id'), 'chat_messages', ['chat_id'], unique=False)
    op.create_table('chunk_extraction_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extraction_depth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generate_embeddings', sa.Boolean(), nullable=False),
    sa.Column('forced_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detected_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('domain_guidance', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('user_instructions', sa.Text(), nullable=True),
    sa.Column('relationship_instructions', sa.Text(), nullable=True),
    sa.Column('user_instructions_template', sa.Text(), nullable=True),
    sa.Column('extraction_rules_template', sa.Text(), nullable=True),
    sa.Column('entity_templates', sa.Text(), nullable=True),
    sa.Column('relationship_templates', sa.Text(), nullable=True),
    sa.Column('domain_examples', sa.Text(), nullable=True),
    sa.Column('extraction_config', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('completed_chunks', sa.Integer(), nullable=False),
    sa.Column('failed_chunks', sa.Integer(), nullable=False),
    sa.Column('finalize_claimed', sa.Boolean(), nullable=False),
    sa.Column('filtered_chunks', sa.Integer(), nullable=True),
    sa.Column('filtered_content_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunk_extraction_jobs_database_name'), 'chunk_extraction_jobs', ['database_name'], unique=False)
    op.create_index(op.f('ix_chunk_extraction_jobs_source_id'), 'chunk_extraction_jobs', ['source_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('group_index', sa.Integer(), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('citation_offset_method', sa.String(length=8), nullable=False),
    sa.Column('embedded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_created_at'), 'document_chunks', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_chunks_database_name'), 'document_chunks', ['database_name'], unique=False)
    op.create_index(op.f('ix_document_chunks_embedded_at'), 'document_chunks', ['embedded_at'], unique=False)
    op.create_index(op.f('ix_document_chunks_source_id'), 'document_chunks', ['source_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_status'), 'document_chunks', ['status'], unique=False)
    op.create_table('extraction_submissions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('chunk_group_index', sa.Integer(), nullable=False),
    sa.Column('entities_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relationships_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('relationship_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('database_name', 'source_id', 'chunk_group_index', name='uq_extraction_sub_source_chunk')
    )
    op.create_index(op.f('ix_extraction_submissions_database_name'), 'extraction_submissions', ['database_name'], unique=False)
    op.create_index('ix_extraction_submissions_source', 'extraction_submissions', ['database_name', 'source_id'], unique=False)
    op.create_index(op.f('ix_extraction_submissions_source_id'), 'extraction_submissions', ['source_id'], unique=False)
    op.create_table('graph_templates',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('database_name', 'source_id', 'template_type', 'name', name='uq_graph_templates_per_source')
    )
    op.create_index(op.f('ix_graph_templates_database_name'), 'graph_templates', ['database_name'], unique=False)
    op.create_index(op.f('ix_graph_templates_is_system'), 'graph_templates', ['is_system'], unique=False)
    op.create_index(op.f('ix_graph_templates_source_id'), 'graph_templates', ['source_id'], unique=False)
    op.create_index(op.f('ix_graph_templates_template_type'), 'graph_templates', ['template_type'], unique=False)
    op.create_table('llm_call_metrics',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('chunk_task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_sequence', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('was_retry', sa.Boolean(), nullable=False),
    sa.Column('retry_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('chunk_size_chars', sa.Integer(), nullable=True),
    sa.Column('entities_extracted', sa.Integer(), nullable=True),
    sa.Column('relationships_extracted', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_call_metrics_chunk_task_id'), 'llm_call_metrics', ['chunk_task_id'], unique=False)
    op.create_index(op.f('ix_llm_call_metrics_database_name'), 'llm_call_metrics', ['database_name'], unique=False)
    op.create_index('ix_llm_call_metrics_database_name_started_at_desc', 'llm_call_metrics', ['database_name', 'started_at'], unique=False)
    op.create_index(op.f('ix_llm_call_metrics_operation_type'), 'llm_call_metrics', ['operation_type'], unique=False)
    op.create_index(op.f('ix_llm_call_metrics_source_id'), 'llm_call_metrics', ['source_id'], unique=False)
    op.create_table('llm_stage_progress',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('stage_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('avg_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('extras_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'stage_name')
    )
    op.create_index('ix_llm_stage_progress_active', 'llm_stage_progress', ['completed_at'], unique=False)
    op.create_table('source_entities',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_entities_database_name'), 'source_entities', ['database_name'], unique=False)
    op.create_index('ix_source_entities_source_confidence', 'source_entities', ['source_id', 'confidence'], unique=False)
    op.create_index(op.f('ix_source_entities_source_id'), 'source_entities', ['source_id'], unique=False)
    op.create_index('ix_source_entities_source_name', 'source_entities', ['source_id', 'name'], unique=False)
    op.create_index('ix_source_entities_source_ordinal', 'source_entities', ['source_id', 'ordinal'], unique=False)
    op.create_index('ix_source_entities_source_type', 'source_entities', ['source_id', 'type'], unique=False)
    op.create_table('source_entity_embeddings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('entity_index', sa.Integer(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_entity_embeddings_source_id'), 'source_entity_embeddings', ['source_id'], unique=False)
    op.create_table('source_recovery_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt_at', sa.DateTime(), nullable=False),
    sa.Column('from_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_taken', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enqueued_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_recovery_events_source_db_time', 'source_recovery_events', ['source_id', 'database_name', 'attempt_at'], unique=False)
    op.create_table('source_tag_assignments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['source_tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'tag_id', name='uq_source_tag_assignment')
    )
    op.create_index(op.f('ix_source_tag_assignments_database_name'), 'source_tag_assignments', ['database_name'], unique=False)
    op.create_index(op.f('ix_source_tag_assignments_source_id'), 'source_tag_assignments', ['source_id'], unique=False)
    op.create_index(op.f('ix_source_tag_assignments_tag_id'), 'source_tag_assignments', ['tag_id'], unique=False)
    op.create_table('triggers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('workflow_inputs', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triggers_database_name'), 'triggers', ['database_name'], unique=False)
    op.create_index(op.f('ix_triggers_event_source'), 'triggers', ['event_source'], unique=False)
    op.create_index(op.f('ix_triggers_user_id'), 'triggers', ['user_id'], unique=False)
    op.create_index(op.f('ix_triggers_workflow_id'), 'triggers', ['workflow_id'], unique=False)
    op.create_table('user_tools',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('system_tool_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['system_tool_id'], ['system_tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tools_database_name'), 'user_tools', ['database_name'], unique=False)
    op.create_index(op.f('ix_user_tools_system_tool_id'), 'user_tools', ['system_tool_id'], unique=False)
    op.create_index(op.f('ix_user_tools_user_id'), 'user_tools', ['user_id'], unique=False)
    op.create_table('vision_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vision_jobs_source_id'), 'vision_jobs', ['source_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('triggered_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('failed_step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    op.create_table('workflow_statistics',
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('successful_executions', sa.Integer(), nullable=False),
    sa.Column('failed_executions', sa.Integer(), nullable=False),
    sa.Column('cancelled_executions', sa.Integer(), nullable=False),
    sa.Column('avg_duration_ms', sa.Integer(), nullable=False),
    sa.Column('min_duration_ms', sa.Integer(), nullable=True),
    sa.Column('max_duration_ms', sa.Integer(), nullable=True),
    sa.Column('last_execution_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    op.create_table('workflow_steps',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('retry_on_failure', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=True),
    sa.Column('continue_on_error', sa.Boolean(), nullable=False),
    sa.Column('thinking_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_workflow_id'), 'workflow_steps', ['workflow_id'], unique=False)
    op.create_table('chunk_extraction_tasks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('hierarchical_group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('small_chunk_ids', sa.JSON(), nullable=True),
    sa.Column('queue_task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('raw_entities', sa.JSON(), nullable=True),
    sa.Column('raw_relationships', sa.JSON(), nullable=True),
    sa.Column('raw_entity_embeddings', sa.JSON(), nullable=True),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('relationship_count', sa.Integer(), nullable=False),
    sa.Column('invalid_relationship_count', sa.Integer(), nullable=False),
    sa.Column('chunk_sentences', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('input_text_length', sa.Integer(), nullable=True),
    sa.Column('llm_response_json', sa.Text(), nullable=True),
    sa.Column('llm_response_length', sa.Integer(), nullable=True),
    sa.Column('llm_duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('context_window_available', sa.Integer(), nullable=True),
    sa.Column('filtering_log', sa.JSON(), nullable=True),
    sa.Column('finish_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('aborted_by_loop', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['chunk_extraction_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunk_extraction_tasks_database_name'), 'chunk_extraction_tasks', ['database_name'], unique=False)
    op.create_index(op.f('ix_chunk_extraction_tasks_job_id'), 'chunk_extraction_tasks', ['job_id'], unique=False)
    op.create_index(op.f('ix_chunk_extraction_tasks_started_at'), 'chunk_extraction_tasks', ['started_at'], unique=False)
    op.create_index(op.f('ix_chunk_extraction_tasks_status'), 'chunk_extraction_tasks', ['status'], unique=False)
    op.create_index('ix_chunk_tasks_job_status', 'chunk_extraction_tasks', ['job_id', 'status'], unique=False)
    op.create_index('ix_chunk_tasks_status_created', 'chunk_extraction_tasks', ['status', 'created_at'], unique=False)
    op.create_table('graph_nodes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('graph_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['graph_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_nodes_database_name'), 'graph_nodes', ['database_name'], unique=False)
    op.create_index('ix_graph_nodes_db_entity_type', 'graph_nodes', ['database_name', 'entity_type'], unique=False)
    op.create_index('ix_graph_nodes_db_source', 'graph_nodes', ['database_name', 'source_id'], unique=False)
    op.create_index('ix_graph_nodes_db_template', 'graph_nodes', ['database_name', 'template_id'], unique=False)
    op.create_index(op.f('ix_graph_nodes_graph_name'), 'graph_nodes', ['graph_name'], unique=False)
    op.create_index(op.f('ix_graph_nodes_source_id'), 'graph_nodes', ['source_id'], unique=False)
    op.create_index(op.f('ix_graph_nodes_template_id'), 'graph_nodes', ['template_id'], unique=False)
    op.create_table('relationship_citations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('edge_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('edge_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('edge_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_entity_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_entity_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('chunk_id', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('justification', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('citation_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_citations_chunk_id'), 'relationship_citations', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_relationship_citations_database_name'), 'relationship_citations', ['database_name'], unique=False)
    op.create_index(op.f('ix_relationship_citations_edge_id'), 'relationship_citations', ['edge_id'], unique=False)
    op.create_index(op.f('ix_relationship_citations_source_id'), 'relationship_citations', ['source_id'], unique=False)
    op.create_table('source_citations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('chunk_id', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('citation_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_citations_chunk_id'), 'source_citations', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_source_citations_database_name'), 'source_citations', ['database_name'], unique=False)
    op.create_index('ix_source_citations_db_entity', 'source_citations', ['database_name', 'entity_uri'], unique=False)
    op.create_index('ix_source_citations_db_source', 'source_citations', ['database_name', 'source_id'], unique=False)
    op.create_index(op.f('ix_source_citations_entity_uri'), 'source_citations', ['entity_uri'], unique=False)
    op.create_index(op.f('ix_source_citations_source_id'), 'source_citations', ['source_id'], unique=False)
    op.create_table('source_relationships',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('source_entity_id', sa.String(), nullable=False),
    sa.Column('target_entity_id', sa.String(), nullable=False),
    sa.Column('predicate', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['source_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['source_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_relationships_database_name'), 'source_relationships', ['database_name'], unique=False)
    op.create_index(op.f('ix_source_relationships_source_entity_id'), 'source_relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_source_relationships_source_id'), 'source_relationships', ['source_id'], unique=False)
    op.create_index('ix_source_relationships_source_ordinal', 'source_relationships', ['source_id', 'ordinal'], unique=False)
    op.create_index(op.f('ix_source_relationships_target_entity_id'), 'source_relationships', ['target_entity_id'], unique=False)
    op.create_table('trigger_executions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_id', sa.String(), nullable=False),
    sa.Column('workflow_execution_id', sa.String(), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_executions_trigger_id'), 'trigger_executions', ['trigger_id'], unique=False)
    op.create_index(op.f('ix_trigger_executions_workflow_execution_id'), 'trigger_executions', ['workflow_execution_id'], unique=False)
    op.create_table('vision_page_descriptions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('vision_job_id', sa.String(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('region_index', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('finish_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vision_job_id'], ['vision_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'page_number', 'region_index', name='uq_vpd_source_page_region')
    )
    op.create_index(op.f('ix_vision_page_descriptions_source_id'), 'vision_page_descriptions', ['source_id'], unique=False)
    op.create_index(op.f('ix_vision_page_descriptions_vision_job_id'), 'vision_page_descriptions', ['vision_job_id'], unique=False)
    op.create_index('ix_vpd_source_status', 'vision_page_descriptions', ['source_id', 'status'], unique=False)
    op.create_table('workflow_step_executions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step_id', sa.String(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_step_executions_execution_id'), 'workflow_step_executions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_workflow_step_executions_step_id'), 'workflow_step_executions', ['step_id'], unique=False)
    op.create_table('chunk_extraction_attempts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_task_id', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('snapshotted_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('input_text_length', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('context_window_available', sa.Integer(), nullable=True),
    sa.Column('llm_response_json', sa.Text(), nullable=True),
    sa.Column('llm_response_length', sa.Integer(), nullable=True),
    sa.Column('llm_duration_ms', sa.Integer(), nullable=True),
    sa.Column('raw_entities', sa.JSON(), nullable=True),
    sa.Column('raw_relationships', sa.JSON(), nullable=True),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('relationship_count', sa.Integer(), nullable=False),
    sa.Column('invalid_relationship_count', sa.Integer(), nullable=False),
    sa.Column('filtering_log', sa.JSON(), nullable=True),
    sa.Column('finish_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('aborted_by_loop', sa.Boolean(), nullable=True),
    sa.Column('chunk_sentences', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_task_id'], ['chunk_extraction_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunk_attempts_task_id', 'chunk_extraction_attempts', ['chunk_task_id', 'attempt_number'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('graph_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('source_node_id', sa.String(), nullable=True),
    sa.Column('target_node_id', sa.String(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['graph_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_edges_database_name'), 'graph_edges', ['database_name'], unique=False)
    op.create_index('ix_graph_edges_db_source_node', 'graph_edges', ['database_name', 'source_node_id'], unique=False)
    op.create_index('ix_graph_edges_db_target_node', 'graph_edges', ['database_name', 'target_node_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_graph_name'), 'graph_edges', ['graph_name'], unique=False)
    op.create_index(op.f('ix_graph_edges_source_id'), 'graph_edges', ['source_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_source_node_id'), 'graph_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_target_node_id'), 'graph_edges', ['target_node_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_template_id'), 'graph_edges', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Baseline is the floor - downgrading below it wipes the DB.

    Alembic's autogen emitted drop_table for every table, which would
    destroy every row on ``alembic downgrade base``. Use the auto-backup
    helper in chaoscypher_core.database.backup for rollback instead.
    """
    pass
