// Copyright (C) 2024-2026 Chaos Cypher, Inc.
// SPDX-License-Identifier: AGPL-3.0-only

// Stryker mutation-testing config for the frontend.
//
// Scope: src/services/api/** — the API client + TanStack Query hooks
// at the React/FastAPI boundary. This is where a typo or a flipped
// conditional silently misroutes user actions, so it gets mutation
// coverage. Mutating the entire src/ tree would take hours; targeted
// scoping keeps the run inside the weekly budget (see ./README.md and
// the make mutate-interface target).
//
// Threshold = ratchet from baseline. Re-baseline (raise `low` /
// `break`) whenever you tighten the suite; see the Makefile recipe.
//
// NOT wired into CI / pre-commit -- it's a manual `make mutate-interface`
// (or `make mutate`) command. mutation testing is slow; making it a PR
// gate would dominate review latency.

/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
export default {
  packageManager: 'npm',
  reporters: ['progress', 'clear-text', 'html', 'json'],
  testRunner: 'vitest',
  vitest: {
    configFile: 'vitest.config.ts',
  },
  // typescript-checker is intentionally OFF. It runs a full project
  // tsc dry-run for the whole src/ tree, which fails before any mutant
  // ever runs because src/types/generated/api.ts is auto-generated by
  // `make types` (Cortex OpenAPI -> TS) and is .gitignored. Requiring
  // that file before mutation testing would force every contributor
  // to spin up Cortex first. The mutated files (src/services/api/*.ts)
  // get type-checked normally as part of CI's `tsc && vite build`
  // step, so missing-typecheck-on-mutants is a tolerable trade.
  // checkers: ['typescript'],
  // tsconfigFile: 'tsconfig.json',

  // Restrict mutation to API surface files that have test coverage.
  // Mutating files with zero tests is wasteful -- every mutant trivially
  // survives so the score gives no signal. The list below mirrors the
  // imports in src/services/api/__tests__/. Add a file here when you
  // add tests for it (or run the broader sweep with the commented-out
  // glob to surface untested files).
  //
  // The 'src/services/api/__tests__/**' exclude is defensive: tests
  // shouldn't be mutated even if a glob accidentally selects them.
  mutate: [
    'src/services/api/upgrade.ts',
    'src/services/api/useChunkDetail.ts',
    'src/services/api/useSourceImages.ts',
    'src/services/api/useVisionPages.ts',
    'src/services/api/graphSnapshot.ts',
    'src/services/api/useGraphSnapshot.ts',
    'src/services/api/queue.ts',
    '!src/services/api/__tests__/**',
    '!src/services/api/**/*.test.ts',
    '!src/services/api/**/*.test.tsx',
  ],

  // 2026-05-19 baseline (6 mutated files: upgrade, useChunkDetail,
  // useSourceImages, useVisionPages, graphSnapshot, useGraphSnapshot):
  //   total mutants : 71
  //   killed        : 51   (71.83% mutation score)
  //   survived      : 12
  //   no coverage   : 8    (graphSnapshot.ts has no direct tests --
  //                          only the hook is tested, which doesn't
  //                          import every export)
  //
  // Ratchet: `break` = baseline (71) - 2 pp = 69. A single risky
  // refactor has wiggle room before failing; a real regression
  // (multiple killed mutants flipping to survived) trips the floor.
  // Bump these whenever you add tests that kill more mutants.
  //
  //   high  -> aspirational; below this is a yellow flag
  //   low   -> warn (Stryker's UI / clear-text reporter highlights)
  //   break -> hard fail; the process exits non-zero
  thresholds: {
    high: 85,
    low: 78,
    break: 78,
  },

  // Concurrency: keep it modest so the harness machine stays usable.
  // Each Stryker worker spawns its own vitest -- which spawns workers
  // of its own; over-subscription causes thrash on most laptops.
  concurrency: 2,

  // Cap the per-test budget so runaway mutants (e.g. infinite loops
  // from a flipped break condition) timeout instead of hanging the
  // whole run. 5s per test is generous for service-layer code that
  // does no real I/O.
  timeoutMS: 5000,

  // Disable type-checking on every mutant -- the global tsconfig run
  // (checkers above) is enough and per-mutant type checks add minutes.
  disableTypeChecks: '{src,test,tests}/**/*.{js,ts,jsx,tsx,mjs,cjs}',

  // Default mutator excludes:
  //   - string literal mutations: noisy for our codebase; we have many
  //     URL paths whose lexical value is the contract (mutating "/api"
  //     to "" is caught by the existing fetch tests anyway).
  // The list mirrors Stryker's "Ignore these mutators" recipe.
  mutator: {
    excludedMutations: ['StringLiteral'],
  },

  // Output goes under reports/ so it can be opened locally without
  // checking artifacts into git. Add `reports/` to .gitignore if you
  // ever commit (the repo-wide .gitignore already excludes generic
  // report dirs).
  htmlReporter: { fileName: 'reports/mutation/index.html' },
  jsonReporter: { fileName: 'reports/mutation/mutation.json' },

  // Skip the auto-clear of the runner cache between mutants -- vitest
  // already isolates test files in workers, and clearing per-mutant
  // adds 1-2s overhead each.
  cleanTempDir: 'always',
};
