# Copyright (C) 2024-2026 Chaos Cypher, Inc.
# SPDX-License-Identifier: AGPL-3.0-only

"""E2E loader smoke matrix.

One test per supported document loader: upload a minimal valid
fixture via the API and assert it reaches ``indexed`` without error.
Doesn't validate extraction quality — that's covered separately —
just "does the loader parse + chunk this file successfully on a
running stack?".

Fixtures are generated by ``e2e/fixtures/generate_loader_samples.py``.

Each test runs with ``extract_entities=False`` so the upload path
exits after indexing without invoking the LLM-extraction pipeline.
That keeps these tests fast (~1-3 s each) and decoupled from any
LLM-quality concerns.
"""

from __future__ import annotations

import time
from pathlib import Path

import httpx
import pytest


# (filename, content-type, marker-substring-expected-in-chunks)
#
# All fixtures contain the word "Alice" so we can sanity-check that
# the indexer not only completed but produced chunks whose content
# survived loader → cleaner → chunker. The PDF + EPUB + DOCX produce
# slightly varied output depending on the library version, so the
# marker check is conservative (case-insensitive substring).
_LOADER_CASES: list[tuple[str, str]] = [
    ("sample.txt", "text/plain"),
    ("sample.md", "text/markdown"),
    ("sample.pdf", "application/pdf"),
    ("sample.csv", "text/csv"),
    ("sample.json", "application/json"),
    ("sample.jsonl", "application/x-ndjson"),
    ("sample.html", "text/html"),
    (
        "sample.docx",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ),
    (
        "sample.xlsx",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ),
    (
        "sample.pptx",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    ),
    ("sample.epub", "application/epub+zip"),
]


def _poll_indexed(client: httpx.Client, source_id: str, timeout: int = 60) -> dict:
    """Wait for ``source_id`` to reach ``indexed`` status.

    Returns the final source detail dict. Raises if the source ends in
    ``error`` or the timeout elapses.
    """
    start = time.time()
    while time.time() - start < timeout:
        resp = client.get(f"/api/v1/sources/{source_id}")
        if resp.status_code == 200:
            data = resp.json()
            status = data.get("processing_status") or data.get("status", "")
            if status == "indexed":
                return data
            if status in ("error", "failed"):
                err = data.get("error_message", "(no message)")
                msg = (
                    f"Source {source_id} ({data.get('filename')}) failed "
                    f"at stage={data.get('error_stage')}: {err}"
                )
                raise RuntimeError(msg)
        time.sleep(0.5)
    raise TimeoutError(f"Source {source_id} did not index within {timeout}s")


@pytest.mark.parametrize(
    ("filename", "content_type"),
    _LOADER_CASES,
    ids=[case[0].rsplit(".", 1)[-1] for case in _LOADER_CASES],
)
def test_loader_indexes_cleanly(
    client: httpx.Client,
    sample_data_dir: str,
    filename: str,
    content_type: str,
) -> None:
    """Every supported loader parses + indexes its minimal fixture."""
    path = Path(sample_data_dir) / filename
    assert path.exists(), f"fixture missing: {path}"

    with path.open("rb") as f:
        upload = client.post(
            "/api/v1/sources",
            files={"file": (filename, f, content_type)},
            data={"extract_entities": "false"},
        )
    assert upload.status_code == 202, f"upload failed: {upload.status_code} {upload.text}"
    source_id = upload.json()["id"]

    detail = _poll_indexed(client, source_id, timeout=60)

    # Sanity: the source was actually indexed (chunks present) and the
    # filename round-tripped. Loaders that produce zero chunks are
    # silent failures we want this test to surface.
    chunks_resp = client.get(f"/api/v1/sources/{source_id}/chunks")
    assert chunks_resp.status_code == 200
    chunks_body = chunks_resp.json()
    total = chunks_body["pagination"]["total"]
    assert total > 0, (
        f"loader '{filename}' produced no chunks; detail.chunk_count="
        f"{detail.get('chunk_count')!r}"
    )
